### ISSUE TITLE
Fail to do npm install

### ISSUE THREAD

**Issue by xyngfei** [amiya-pattnaik/webdriverIO-with-cucumberBDD#11]
I hv encountered this issue when I did npm i. Any suggestion?

[11:26:41] Fixing AndroidManifest icon bug

> appium-windows-driver@1.5.1 install /Users/xyngfei/Documents/workspace/webdriverIO-with-cucumberBDD/node_modules/appium/node_modules/appium-windows-driver
> node install-npm.js

Not installing WinAppDriver since did not detect a Windows system

> fibers@2.0.2 install /Users/xyngfei/Documents/workspace/webdriverIO-with-cucumberBDD/node_modules/fibers
> node build.js || nodejs build.js

  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:318:3: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
                object->SetAccessor(isolate->GetCurrentContext(), name, (AccessorNameGetterCallback)getter, (AccessorNameSetterCallback)setter);
                ^~~~~~~~~~~~~~~~~~~
../src/fibers.cc:464:24: warning: 'Utf8Value' is deprecated: Use Isolate version [-Wdeprecated-declarations]
                                        String::Utf8Value stack(uni::Deref(that.isolate, fatal_stack));
                                                          ^
/Users/xyngfei/.node-gyp/11.3.0/include/node/v8.h:2991:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/xyngfei/.node-gyp/11.3.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/fibers.cc:686:66: error: too few arguments to function call, expected at least 2, have 1
                                Script::Compile(uni::NewLatin1String(that.isolate, "void 0;"));
                                ~~~~~~~~~~~~~~~                                              ^
/Users/xyngfei/.node-gyp/11.3.0/include/node/v8.h:1359:3: note: 'Compile' declared here
  static V8_WARN_UNUSED_RESULT MaybeLocal<Script> Compile(
  ^
../src/fibers.cc:701:66: error: too few arguments to function call, single argument 'context' was not specified
                                                uni::Reset(that.isolate, fatal_stack, try_catch.StackTrace());
                                                                                      ~~~~~~~~~~~~~~~~~~~~ ^
/Users/xyngfei/.node-gyp/11.3.0/include/node/v8.h:8878:3: note: 'StackTrace' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> StackTrace(
  ^
/Users/xyngfei/.node-gyp/11.3.0/include/node/v8config.h:418:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
2 warnings and 2 errors generated.
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/11.3.0_1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/xyngfei/Documents/workspace/webdriverIO-with-cucumberBDD/node_modules/fibers
gyp ERR! node -v v11.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm WARN eslint-plugin-import@2.17.3 requires a peer of eslint@2.x - 5.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard@10.2.1 requires a peer of eslint@>=3.19.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-node@5.2.1 requires a peer of eslint@>=3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-standard@3.1.0 requires a peer of eslint@>=3.19.0 but none is installed. You must install peer dependencies yourself.
npm WARN webdriverIO-with-cucumberBDD@1.1.5 No repository field.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@2.0.2 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xyngfei/.npm/_logs/2019-05-27T03_26_51_258Z-debug.log

**Comment by xyngfei** [comment]
I did try to install `npm install -g node-gyp@3.8` to ensure I can use node-gyp command globally. However, I still get the same issue.
