### ISSUE TITLE
Error in "Performing a login: Performing login operation with passing test data as data table: Given I am on the phptravels page" browser.compareScreen is not a function

### ISSUE THREAD

**Issue by pearlberry** [amiya-pattnaik/webdriverIO-with-cucumberBDD#17]
I've followed the installation steps and have not modified anything in the framework, running out of the box, I get this error immediately.
Any help would be appreciated.
```
> wdio ./test/config/suite.cucumber.conf.js

2020-02-24T21:19:08.414Z DEBUG @wdio/sync: Couldn't load fibers package for Node v10 and above
2020-02-24T21:19:08.414Z DEBUG @wdio/sync: Couldn't load fibers package for Node v8

Execution of 2 spec files started at 2020-02-24T21:19:09.517Z

[0-0] RUNNING in chrome - C:\webdriverIO-with-cucumberBDD-master\test\features\ta-login.feature
[0-1] RUNNING in chrome - C:\webdriverIO-with-cucumberBDD-master\test\features\yahoo-search.feature
[0-0] Error in "Performing a login: Performing login operation with passing test data as data table: Given I am on the phptravels page"
browser.compareScreen is not a function
[0-1] Error in "Performing a Yahoo Search: Performing a search operation: Given I am on the search page"
expected {} to equal 'Yahoo Search - Web Search'
[0-1] Error in "Performing a Yahoo Search: Performing a search operation with passing test data as data table: Given I am on the search page"
expected {} to equal 'Yahoo Search - Web Search'
[0-1] FAILED in chrome - C:\webdriverIO-with-cucumberBDD-master\test\features\yahoo-search.feature
[0-0] FAILED in chrome - C:\webdriverIO-with-cucumberBDD-master\test\features\ta-login.feature

 "spec" Reporter:
------------------------------------------------------------------
[chrome 79.0.3945.130 Windows NT #0-1] Spec: C:\webdriverIO-with-cucumberBDD-master\test\features\yahoo-search.feature
[chrome 79.0.3945.130 Windows NT #0-1] Running: chrome (v79.0.3945.130) on Windows NT
[chrome 79.0.3945.130 Windows NT #0-1]
[chrome 79.0.3945.130 Windows NT #0-1] Performing a Yahoo Search
[chrome 79.0.3945.130 Windows NT #0-1]     Performing a search operation
[chrome 79.0.3945.130 Windows NT #0-1]        ✖ Given I am on the search page
[chrome 79.0.3945.130 Windows NT #0-1]        - When I enter "Selenium Webdriver" into the search box
[chrome 79.0.3945.130 Windows NT #0-1]        - And I click the search button
[chrome 79.0.3945.130 Windows NT #0-1]        - Then I should see a list of search results
[chrome 79.0.3945.130 Windows NT #0-1]
[chrome 79.0.3945.130 Windows NT #0-1]     Performing a search operation with passing test data as data table
[chrome 79.0.3945.130 Windows NT #0-1]        ✖ Given I am on the search page
[chrome 79.0.3945.130 Windows NT #0-1]        - When I enter "Selenium Webdriver" into the search box
[chrome 79.0.3945.130 Windows NT #0-1]        - And I click the search button
[chrome 79.0.3945.130 Windows NT #0-1]        - Then I should see a list of search results
[chrome 79.0.3945.130 Windows NT #0-1]
[chrome 79.0.3945.130 Windows NT #0-1] 2 failing (7.5s)
[chrome 79.0.3945.130 Windows NT #0-1] 6 skipped
[chrome 79.0.3945.130 Windows NT #0-1]
[chrome 79.0.3945.130 Windows NT #0-1] 1) Performing a search operation Given I am on the search page
[chrome 79.0.3945.130 Windows NT #0-1] expected {} to equal 'Yahoo Search - Web Search'
[chrome 79.0.3945.130 Windows NT #0-1] AssertionError: expected {} to equal 'Yahoo Search - Web Search'
[chrome 79.0.3945.130 Windows NT #0-1]     at World.<anonymous> (C:\webdriverIO-with-cucumberBDD-master\test\stepDefinitions/given.js:9:29)
[chrome 79.0.3945.130 Windows NT #0-1]     at World.executeAsync (C:\webdriverIO-with-cucumberBDD-master\node_modules\@wdio\cucumber-framework\node_modules\@wdio\utils\build\shim.js:68:13)
[chrome 79.0.3945.130 Windows NT #0-1]     at World.testFrameworkFnWrapper (C:\webdriverIO-with-cucumberBDD-master\node_modules\@wdio\cucumber-framework\node_modules\@wdio\utils\build\test-framework\testFnWrapper.js:55:28)
[chrome 79.0.3945.130 Windows NT #0-1]     at <anonymous>
[chrome 79.0.3945.130 Windows NT #0-1]
[chrome 79.0.3945.130 Windows NT #0-1] 2) Performing a search operation with passing test data as data table Given I am on the search page
[chrome 79.0.3945.130 Windows NT #0-1] expected {} to equal 'Yahoo Search - Web Search'
[chrome 79.0.3945.130 Windows NT #0-1] AssertionError: expected {} to equal 'Yahoo Search - Web Search'
[chrome 79.0.3945.130 Windows NT #0-1]     at World.<anonymous> (C:\webdriverIO-with-cucumberBDD-master\test\stepDefinitions/given.js:9:29)
[chrome 79.0.3945.130 Windows NT #0-1]     at World.executeAsync (C:\webdriverIO-with-cucumberBDD-master\node_modules\@wdio\cucumber-framework\node_modules\@wdio\utils\build\shim.js:68:13)
[chrome 79.0.3945.130 Windows NT #0-1]     at World.testFrameworkFnWrapper (C:\webdriverIO-with-cucumberBDD-master\node_modules\@wdio\cucumber-framework\node_modules\@wdio\utils\build\test-framework\testFnWrapper.js:55:28)
[chrome 79.0.3945.130 Windows NT #0-1]     at <anonymous>
------------------------------------------------------------------
[chrome 79.0.3945.130 Windows NT #0-0] Spec: C:\webdriverIO-with-cucumberBDD-master\test\features\ta-login.feature
[chrome 79.0.3945.130 Windows NT #0-0] Running: chrome (v79.0.3945.130) on Windows NT
[chrome 79.0.3945.130 Windows NT #0-0]
[chrome 79.0.3945.130 Windows NT #0-0] Performing a login
[chrome 79.0.3945.130 Windows NT #0-0]     Performing login operation with passing test data as data table
[chrome 79.0.3945.130 Windows NT #0-0]        ✖ Given I am on the phptravels page
[chrome 79.0.3945.130 Windows NT #0-0]        - When I login with username and password "user@phptravels.com" "demouser" into the text box
[chrome 79.0.3945.130 Windows NT #0-0]        - Then I should see the message "Hi, Demo User" on my account page
[chrome 79.0.3945.130 Windows NT #0-0]
[chrome 79.0.3945.130 Windows NT #0-0] 1 failing (8s)
[chrome 79.0.3945.130 Windows NT #0-0] 2 skipped
[chrome 79.0.3945.130 Windows NT #0-0]
[chrome 79.0.3945.130 Windows NT #0-0] 1) Performing login operation with passing test data as data table Given I am on the phptravels page
[chrome 79.0.3945.130 Windows NT #0-0] browser.compareScreen is not a function
[chrome 79.0.3945.130 Windows NT #0-0] TypeError: browser.compareScreen is not a function
[chrome 79.0.3945.130 Windows NT #0-0]     at World.<anonymous> (C:\webdriverIO-with-cucumberBDD-master\test\stepDefinitions/given.js:15:18)
[chrome 79.0.3945.130 Windows NT #0-0]     at World.executeAsync (C:\webdriverIO-with-cucumberBDD-master\node_modules\@wdio\cucumber-framework\node_modules\@wdio\utils\build\shim.js:68:13)
[chrome 79.0.3945.130 Windows NT #0-0]     at World.testFrameworkFnWrapper (C:\webdriverIO-with-cucumberBDD-master\node_modules\@wdio\cucumber-framework\node_modules\@wdio\utils\build\test-framework\testFnWrapper.js:55:28)
[chrome 79.0.3945.130 Windows NT #0-0]     at <anonymous>


Spec Files:      0 passed, 2 failed, 2 total (100% completed) in 00:00:17

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webdriverIO-with-cucumberBDD@1.1.6 test: `wdio ./test/config/suite.cucumber.conf.js`
npm ERR! Exit status 1
```

**Comment by nickjtorres** [comment]
@pearlberry Node version? $node -v

**Comment by amiya-pattnaik** [comment]
@pearlberry 
maybe you can try remove node_modules and reinstall it. If it does not work, then  delete package lock before installing packages? Make sure node fibers of version 4.0.2 is installed laverdet/node-fibers#424

**Comment by fedika** [comment]
Hi @amiya-pattnaik 
Thank you for boilerplate project

In this case, I also got this issue when perform npm run test

The result for phptravel is
TypeError: browser.compareScreen is not a function

node version is v12.13.0
fibers is installed with v4.0.2

but it keeps getting failed on compareScreen

**Comment by amiya-pattnaik** [comment]
Please take the latest boilerplate code for V6 version
