### ISSUE TITLE
npm update fails on v8::Object::SetHiddenValue

### ISSUE THREAD

**Issue by ywarnier** [amiya-pattnaik/webdriverIO-with-cucumberBDD#2]
I'm on Ubuntu 17.10. I clone the master branch of your repo and launch `npm update' in it.

This gives me the following error:
```
> java@0.7.2 install /var/www/webdriverIO-with-cucumberBDD/node_modules/java
> node-gyp rebuild

make : on entre dans le répertoire « /var/www/webdriverIO-with-cucumberBDD/node_modules/java/build »
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
In file included from ../node_modules/nan/nan.h:196:0,
                 from ../src/java.h:9,
                 from ../src/java.cpp:1:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::MaybeLocal<v8::Object> Nan::CloneElementAt(v8::Local<v8::Array>, uint32_t)’:
../node_modules/nan/nan_maybe_43_inl.h:220:58: warning: ‘v8::MaybeLocal<v8::Object> v8::Array::CloneElementAt(v8::Local<v8::Context>, uint32_t)’ is deprecated: Cloning is not supported. [-Wdeprecated-declarations]
   return array->CloneElementAt(GetCurrentContext(), index);
                                                          ^
In file included from ~/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from ../src/java.h:5,
                 from ../src/java.cpp:1:
~/.node-gyp/8.9.4/include/node/v8.h:3502:36: note: declared here
                 MaybeLocal<Object> CloneElementAt(Local<Context> context,
                                    ^
~/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../node_modules/nan/nan_new.h:189:0,
                 from ../node_modules/nan/nan.h:202,
                 from ../src/java.h:9,
                 from ../src/java.cpp:1:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::BooleanObject>::return_t Nan::imp::Factory<v8::BooleanObject>::New(bool)’:
../node_modules/nan/nan_implementation_12_inl.h:40:38: warning: ‘static v8::Local<v8::Value> v8::BooleanObject::New(bool)’ is deprecated: Pass an isolate [-Wdeprecated-declarations]
   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                      ^
In file included from ~/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from ../src/java.h:5,
                 from ../src/java.cpp:1:
~/.node-gyp/8.9.4/include/node/v8.h:4793:56: note: declared here
   V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                        ^
~/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/java.h:9:0,
                 from ../src/java.cpp:1:
../node_modules/nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’:
../node_modules/nan/nan.h:2023:16: warning: ‘bool v8::Object::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     , attribute);
                ^
In file included from ~/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from ../src/java.h:5,
                 from ../src/java.cpp:1:
~/.node-gyp/8.9.4/include/node/v8.h:3172:22: note: declared here
                 bool SetAccessor(Local<Name> name,
                      ^
~/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/java.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Java::newByte(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/java.cpp:897:49: warning: ‘v8::Local<v8::Number> v8::Value::ToNumber() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Number> val = info[0]->ToNumber();
                                                 ^
In file included from ../src/java.h:5:0,
                 from ../src/java.cpp:1:
~/.node-gyp/8.9.4/include/node/v8.h:9707:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^~~~~
../src/java.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Java::newShort(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/java.cpp:927:49: warning: ‘v8::Local<v8::Number> v8::Value::ToNumber() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Number> val = info[0]->ToNumber();
                                                 ^
In file included from ../src/java.h:5:0,
                 from ../src/java.cpp:1:
~/.node-gyp/8.9.4/include/node/v8.h:9707:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^~~~~
../src/java.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Java::newLong(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/java.cpp:956:49: warning: ‘v8::Local<v8::Number> v8::Value::ToNumber() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Number> val = info[0]->ToNumber();
                                                 ^
In file included from ../src/java.h:5:0,
                 from ../src/java.cpp:1:
~/.node-gyp/8.9.4/include/node/v8.h:9707:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^~~~~
../src/java.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Java::newChar(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/java.cpp:983:51: warning: ‘v8::Local<v8::Number> v8::Value::ToNumber() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     v8::Local<v8::Number> val = info[0]->ToNumber();
                                                   ^
In file included from ../src/java.h:5:0,
                 from ../src/java.cpp:1:
~/.node-gyp/8.9.4/include/node/v8.h:9707:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^~~~~
../src/java.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Java::newFloat(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/java.cpp:1019:49: warning: ‘v8::Local<v8::Number> v8::Value::ToNumber() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Number> val = info[0]->ToNumber();
                                                 ^
In file included from ../src/java.h:5:0,
                 from ../src/java.cpp:1:
~/.node-gyp/8.9.4/include/node/v8.h:9707:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^~~~~
../src/java.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Java::newDouble(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/java.cpp:1044:49: warning: ‘v8::Local<v8::Number> v8::Value::ToNumber() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Number> val = info[0]->ToNumber();
                                                 ^
In file included from ../src/java.h:5:0,
                 from ../src/java.cpp:1:
~/.node-gyp/8.9.4/include/node/v8.h:9707:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^~~~~
../src/java.cpp: In function ‘void EIO_AfterCallJs(uv_work_t*)’:
../src/java.cpp:1263:16: warning: ‘v8::TryCatch::TryCatch()’ is deprecated: Use isolate version [-Wdeprecated-declarations]
   v8::TryCatch tryCatch;
                ^~~~~~~~
In file included from ~/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from ../src/java.h:5,
                 from ../src/java.cpp:1:
~/.node-gyp/8.9.4/include/node/v8.h:8260:40: note: declared here
   V8_DEPRECATED("Use isolate version", TryCatch());
                                        ^
~/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/javaObject.o
In file included from ../node_modules/nan/nan.h:196:0,
                 from ../src/utils.h:12,
                 from ../src/methodCallBaton.h:5,
                 from ../src/javaObject.h:10,
                 from ../src/javaObject.cpp:1:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::MaybeLocal<v8::Object> Nan::CloneElementAt(v8::Local<v8::Array>, uint32_t)’:
../node_modules/nan/nan_maybe_43_inl.h:220:58: warning: ‘v8::MaybeLocal<v8::Object> v8::Array::CloneElementAt(v8::Local<v8::Context>, uint32_t)’ is deprecated: Cloning is not supported. [-Wdeprecated-declarations]
   return array->CloneElementAt(GetCurrentContext(), index);
                                                          ^
In file included from ~/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from ../src/javaObject.h:5,
                 from ../src/javaObject.cpp:1:
~/.node-gyp/8.9.4/include/node/v8.h:3502:36: note: declared here
                 MaybeLocal<Object> CloneElementAt(Local<Context> context,
                                    ^
~/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../node_modules/nan/nan_new.h:189:0,
                 from ../node_modules/nan/nan.h:202,
                 from ../src/utils.h:12,
                 from ../src/methodCallBaton.h:5,
                 from ../src/javaObject.h:10,
                 from ../src/javaObject.cpp:1:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::BooleanObject>::return_t Nan::imp::Factory<v8::BooleanObject>::New(bool)’:
../node_modules/nan/nan_implementation_12_inl.h:40:38: warning: ‘static v8::Local<v8::Value> v8::BooleanObject::New(bool)’ is deprecated: Pass an isolate [-Wdeprecated-declarations]
   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                      ^
In file included from ~/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from ../src/javaObject.h:5,
                 from ../src/javaObject.cpp:1:
~/.node-gyp/8.9.4/include/node/v8.h:4793:56: note: declared here
   V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                        ^
~/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/utils.h:12:0,
                 from ../src/methodCallBaton.h:5,
                 from ../src/javaObject.h:10,
                 from ../src/javaObject.cpp:1:
../node_modules/nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’:
../node_modules/nan/nan.h:2023:16: warning: ‘bool v8::Object::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     , attribute);
                ^
In file included from ~/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from ../src/javaObject.h:5,
                 from ../src/javaObject.cpp:1:
~/.node-gyp/8.9.4/include/node/v8.h:3172:22: note: declared here
                 bool SetAccessor(Local<Name> name,
                      ^
~/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/javaObject.cpp: In static member function ‘static v8::Local<v8::Object> JavaObject::New(Java*, jobject)’:
../src/javaObject.cpp:116:59: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Object> javaObjectObj = ctor->NewInstance();
                                                           ^
In file included from ~/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from ../src/javaObject.h:5,
                 from ../src/javaObject.cpp:1:
~/.node-gyp/8.9.4/include/node/v8.h:3836:52: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                    ^
~/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/javaObject.cpp:117:18: error: ‘class v8::Object’ has no member named ‘SetHiddenValue’; did you mean ‘IntegerValue’?
   javaObjectObj->SetHiddenValue(Nan::New<v8::String>(V8_HIDDEN_MARKER_JAVA_OBJECT).ToLocalChecked(), Nan::New<v8::Boolean>(true));
                  ^~~~~~~~~~~~~~
                  IntegerValue
../src/javaObject.cpp: In static member function ‘static v8::Local<v8::Object> JavaProxyObject::New(Java*, jobject, DynamicProxyData*)’:
../src/javaObject.cpp:349:59: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Object> javaObjectObj = ctor->NewInstance();
                                                           ^
In file included from ~/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from ../src/javaObject.h:5,
                 from ../src/javaObject.cpp:1:
~/.node-gyp/8.9.4/include/node/v8.h:3836:52: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                    ^
~/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/javaObject.cpp:350:18: error: ‘class v8::Object’ has no member named ‘SetHiddenValue’; did you mean ‘IntegerValue’?
   javaObjectObj->SetHiddenValue(Nan::New<v8::String>(V8_HIDDEN_MARKER_JAVA_OBJECT).ToLocalChecked(), Nan::New<v8::Boolean>(true));
                  ^~~~~~~~~~~~~~
                  IntegerValue
nodejavabridge_bindings.target.mk:106 : la recette pour la cible « Release/obj.target/nodejavabridge_bindings/src/javaObject.o » a échouée
make: *** [Release/obj.target/nodejavabridge_bindings/src/javaObject.o] Erreur 1
make : on quitte le répertoire « /var/www/webdriverIO-with-cucumberBDD/node_modules/java/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.13.0-32-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/webdriverIO-with-cucumberBDD/node_modules/java
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN webdriverIO-with-cucumberBDD@1.1.3 No repository field.
npm WARN webdriverIO-with-cucumberBDD@1.1.3 scripts['tests'] should probably be scripts['test'].
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the java@0.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2018-02-12T15_06_51_532Z-debug.log
```

Does that ring a bell? Is that something I can fix by changing some of the dependencies?
I appreciate your time.

**Comment by amiya-pattnaik** [comment]
Hi Ywarnier,
I am not sure is because of the clone or not. You can try with `npm install` . But the error which you are getting related to java is due to the jdbc module is not getting installed.  Please refer to below links for set up : https://www.npmjs.com/package/node-gyp
 or https://github.com/amiya-pattnaik/webdriverIO-with-cucumberBDD/issues/1    . (See the reply from jaffamonkey )

If you don't want database module, then you can remove the `node-any-jdbc` module and also comment the database common methods from the common-utilities.js file. you should be good to proceed.

On the second issue related to Chai, it has entries in package.json and you should not face any issue. Please check whether chai module is being installed or not.

Thanks,
Amiya

**Comment by amiya-pattnaik** [comment]
closing this issue assuming that above steps helped in resolving the issue.
